import { FingerspellInfo } from "@/typings";
import { Consonant, Vowel } from "./letters";

export const 자음: Record<Consonant, FingerspellInfo> = {
  "": { signs: [] as string[] },
  ㄱ: { signs: ["00"] },
  ㄲ: { signs: ["00", "00"] },
  ᆪ: { signs: ["00", "06"] },
  ㄴ: { signs: ["01"] },
  ᆬ: { signs: ["01", "08"] },
  ᆭ: { signs: ["01", "13"] },
  ㄷ: { signs: ["02"] },
  ㄸ: { signs: ["02", "02"] },
  ㄹ: { signs: ["03"] },
  ᆰ: { signs: ["03", "00"] },
  ᆱ: { signs: ["03", "04"] },
  ᆲ: { signs: ["03", "05"] },
  ᆳ: { signs: ["03", "06"] },
  ᆴ: { signs: ["03", "11"] },
  ᆵ: { signs: ["03", "12"] },
  ᆶ: { signs: ["03", "13"] },
  ㅁ: { signs: ["04"] },
  ㅂ: { signs: ["05"] },
  ㅃ: { signs: ["05", "05"] },
  ᆹ: { signs: ["05", "06"] },
  ㅅ: { signs: ["06"] },
  ㅆ: { signs: ["06", "06"] },
  ㅇ: { signs: ["07"] },
  ㅈ: { signs: ["08"] },
  ㅉ: { signs: ["08", "08"] },
  ㅊ: { signs: ["09"] },
  ㅋ: { signs: ["10"] },
  ㅌ: { signs: ["11"] },
  ㅍ: { signs: ["12"] },
  ㅎ: { signs: ["13"] },
};

export const 모음: Record<Vowel, FingerspellInfo> = {
  ㅏ: { position: "right" as const, signs: ["00"] },
  ㅐ: { position: "right" as const, signs: ["01"] },
  ㅑ: { position: "right" as const, signs: ["02"] },
  ㅒ: { position: "right" as const, signs: ["03"] },
  ㅓ: { position: "right" as const, signs: ["04"] },
  ㅔ: { position: "right" as const, signs: ["05"] },
  ㅕ: { position: "right" as const, signs: ["06"] },
  ㅖ: { position: "right" as const, signs: ["07"] },
  ㅗ: { position: "bottom" as const, signs: ["08"] },
  ㅘ: { position: "bottom" as const, signs: ["08", "00"] },
  ㅙ: { position: "bottom" as const, signs: ["08", "01"] },
  ㅚ: { position: "bottom" as const, signs: ["09"] },
  ㅛ: { position: "bottom" as const, signs: ["10"] },
  ㅜ: { position: "bottom" as const, signs: ["11"] },
  ㅝ: { position: "bottom" as const, signs: ["11", "04"] },
  ㅞ: { position: "bottom" as const, signs: ["11", "05"] },
  ㅟ: { position: "bottom" as const, signs: ["12"] },
  ㅠ: { position: "bottom" as const, signs: ["13"] },
  ㅡ: { position: "bottom" as const, signs: ["14"] },
  ㅢ: { position: "bottom" as const, signs: ["15"] },
  ㅣ: { position: "right" as const, signs: ["16"] },
};
